[CmdCtrlConfig]
ListenAddress = "0.0.0.0:4445"
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"
UseTLS = true
Enabled = true

[OortGroupStoreConfig]
ListenAddress = "0.0.0.0:6380"
MaxClients = 8192
Profile = false
Debug = false
InsecureSkipVerify = true
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"

[GroupStoreConfig]
CompactionInterval = 42
ValueCap = 4194302
Path = "/data"

[TCPMsgRingConfig]
UseTLS = true
CertFile = "/etc/oort/server.crt"
KeyFile = "/etc/oort/server.key"

